name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out a repo
      - uses: psf/black@stable
        name: Run linter on src
        with:
          options: "--check --verbose -l 120"
          src: "./src"
          version: "~= 22.0"
      - uses: psf/black@stable
        name: Run linter on scripts
        with:
          options: "--check --verbose -l 120"
          src: "./src"
          version: "~= 22.0"
