name: Data Collection

on: [push, pull_request, workflow_dispatch]

env:
  COMMAND_OPTIONS: '-r --base-dir=/bin/'

jobs:
  opensuse_data_collection:
    strategy:
      matrix:
        os: [ manjaro, ubuntu, opensuse ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checking out a repo
      - run: docker pull danilapechenev/instruction-analysis:${{ matrix.os }}
        name: Getting a docker image from Docker Hub
      - run: echo "TIME=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
        name: Getting current time
      - run: echo "IMAGE_SHA=$(docker inspect --format='{{.Parent}}' danilapechenev/instruction-analysis:${{ matrix.os }} | cut -c 8-)" >> $GITHUB_ENV
        name: Getting hash of the image
      - uses: addnab/docker-run-action@v3
        name: Running docker container
        with:
          image: danilapechenev/instruction-analysis:${{ matrix.os }}
          options: -v ${{ github.workspace }}:/DataCollection:rw
          run: |
            cd DataCollection
            python3 -m venv venv
            . ./venv/bin/activate
            python3 -m pip install -r requirements.txt
            python3 src/data_collection.py ${{ env.COMMAND_OPTIONS }} /DataCollection/${{ matrix.os }}_${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}.csv
      - uses: actions/upload-artifact@v3
        name: Saving data as artifact of workflow
        with:
          name: ${{ matrix.os }}_${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}
          path: ${{ github.workspace }}/${{ matrix.os }}_${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}.csv
