name: Data Collection

on: [push, pull_request]

jobs:

  manjaro:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: addnab/docker-run-action@v3
      with:
        image: manjarolinux/base:20230226
        options: -v ${{ github.workspace }}:/DataCollection:rw
        run: |
          pacman -S --noconfirm binutils
          cd DataCollection
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python data_collection.py --base-dir=/bin /DataCollection/manjaro_data.csv
    - uses: actions/upload-artifact@v3
      with:
        name: manjaro_data
        path: DataCollection/manjaro_data.csv