name: Data Collection

on: [push, pull_request]

jobs:

  manjaro:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build -f dockerfiles/DockerfileManjaro -t manjaro_dc .
      - run: echo "TIME=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
      - run: echo "IMAGE_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' manjaro_dc | cut -c 19-)" >> $GITHUB_ENV
      - uses: addnab/docker-run-action@v3
        with:
          image: manjaro_dc
          options: -v ${{ github.workspace }}:/DataCollection:rw
          run: |
            cd DataCollection
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python data_collection.py /DataCollection/${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}.csv
      - uses: actions/upload-artifact@v3
        with:
          name: manjaro_data
          path: ${{ github.workspace }}/${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}.csv