name: Manjaro Data Collection

on: [push, pull_request, workflow_dispatch]

env:
  COMMAND_OPTIONS: '-r --base-dir=/bin/'

jobs:
  manjaro_data_collection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checking out a repo
      - run: docker build -f dockerfiles/DockerfileManjaro -t manjaro_dc .
        name: Building a docker image
      - run: echo "TIME=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
        name: Getting current time
      - run: echo "IMAGE_SHA=$(docker inspect --format='{{.Parent}}' manjaro_dc | cut -c 8-)" >> $GITHUB_ENV
        name: Getting hash of the image
      - uses: addnab/docker-run-action@v3
        name: Running docker container
        with:
          image: manjaro_dc
          options: -v ${{ github.workspace }}:/DataCollection:rw
          run: |
            cd DataCollection
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python src/data_collection.py ${{ env.COMMAND_OPTIONS }} /DataCollection/manjaro_${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}.csv
      - uses: actions/upload-artifact@v3
        name: Saving data as artifact of workflow
        with:
          name: manjaro_${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}
          path: ${{ github.workspace }}/manjaro_${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}.csv
