name: Publish Manjaro Docker Image

on: [push, pull_request, workflow_dispatch]

jobs:
  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: danilapechenev
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image & Push
        run: |
          for os in $(git diff --name-only HEAD~1 | grep "dockerfiles/*" | while read line ; do echo "${line#*.}" ; done);
          docker build . --file dockerfiles/Dockerfile.${{ matrix.os }} --tag danilapechenev/instruction-analysis:${{ matrix.os }};
          docker push danilapechenev/instruction-analysis:${{ matrix.os }};
          done
