name: Publish Manjaro Docker Image

on: [push, pull_request, workflow_dispatch]

jobs:
  get_changed_files:
    name: Get changed files
    steps:
      - name: Run bash command
        run: echo "OS=$(git diff --name-only HEAD~1 | grep "dockerfiles/*" | while read line ; do echo "${line#*.}" ; done)" >> $GITHUB_ENV
  push_to_dockerhub:
    strategy:
      matrix:
        os: ${{ env.OS }}
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: danilapechenev
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file dockerfiles/Dockerfile.${{ matrix.os }} --tag danilapechenev/instruction-analysis:${{ matrix.os }}
      - name: Push
        run: docker push danilapechenev/instruction-analysis:${{ matrix.os }}
