name: Build & Publish Docker Images

on: [push, pull_request, workflow_dispatch]

jobs:
  push_to_dockerhub:
    name: Build & Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: danilapechenev
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker images & Push
        run: |
          for os in $(git diff --name-only --diff-filter=ACMRT ${{ github.sha }} | grep "dockerfiles/*" | while read line ; do echo "${line#*.}" ; done); do
            docker build . --file dockerfiles/Dockerfile.$os --tag danilapechenev/instruction-analysis:$os
            docker push danilapechenev/instruction-analysis:$os
          done
