name: Ubuntu Data Collection

on: [push, pull_request, workflow_dispatch]

env:
  COMMAND_OPTIONS: '-r --base-dir=/bin/'

jobs:
  manjaro_data_collection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checking out a repo
      - run: docker build -f dockerfiles/DockerfileUbuntu -t ubuntu_dc .
        name: Building a docker image
      - run: echo "TIME=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
        name: Getting current time
      - run: echo "IMAGE_SHA=$(docker inspect --format='{{.Parent}}' ubuntu_dc | cut -c 8-)" >> $GITHUB_ENV
        name: Getting hash of the image
      - uses: addnab/docker-run-action@v3
        name: Running docker container
        with:
          image: ubuntu_dc
          options: -v ${{ github.workspace }}:/DataCollection:rw
          run: |
            cd DataCollection
            python3.10 -m venv venv
            . ./venv/bin/activate
            python3.10 -m pip install -r requirements.txt
            python3.10 src/data_collection.py ${{ env.COMMAND_OPTIONS }} /DataCollection/ubuntu_${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}.csv
      - uses: actions/upload-artifact@v3
        name: Saving data as artifact of workflow
        with:
          name: ubuntu_${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}
          path: ${{ github.workspace }}/ubuntu_${{ env.TIME }}_${{ env.IMAGE_SHA }}_${{ github.sha }}.csv
